# Generated by Django 4.1.7 on 2025-05-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='myText',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name=''),
        ),
    ]
