# Generated by Django 4.1.7 on 2025-05-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_category_mytext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='myText',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
